### ISSUE TITLE
No usage documentation :(

### ISSUE THREAD

**Issue by soumyaray** [SOAupstart2/Team-HW-1-Ideate-and-Scrape#16]
Please put an example in your README of how to use the gem from command line, and one example of how to use it from code.

**Comment by stonegold546** [comment]
Our first gem takes in no argument. You simply run `codeschool` from the command line and it puts the result into the command line :)

**Comment by soumyaray** [comment]
ah ok.  still, a basic example of doing that on the command line would be helpful. as would a simple example of calling it in code that we could copy-paste.

**Comment by stonegold546** [comment]
Currently, we have only the command in the README. So if we show sample output, that'd be good?

**Comment by soumyaray** [comment]
Maybe just a quick example of how to require and call it in Ruby code?  It is a Ruby gem, so programmers would be interested...

**Comment by stonegold546** [comment]
All right! @stozuka and I trying to find out how to use our gem inside code :)

**Comment by stonegold546** [comment]
@soumyaray I think we've just set this up.

**Comment by soumyaray** [comment]
:+1: Looks good! Closing this one.

**Comment by stonegold546** [comment]
Thanks!
