### ISSUE TITLE
Why Nokogiri?

### ISSUE THREAD

**Issue by soumyaray** [SOAupstart2/Team-HW-1-Ideate-and-Scrape#17]
I'm curious why you are using Nokogiri instead of Oga?  Here are the pros and cons as I know them:

**Nokogiri**
- Pros: Fast (uses native C or Java extensions)
- Cons: 
  - Tied to C or Java, so difficult to install and dependent on version of Ruby (CRuby/JRuby)
  - Requires Unix libraries like libxml which means it won't run on Windows machines, and libxml often breaks or is changed when OSX upgrades

**Oga**
- Pros: Pure Ruby so runs anywhere, no installation requirements
- Cons: Slower than Nokogiri

**Comment by stonegold546** [comment]
@stozuka already wrote the scrape code for the first gem using Nokogiri. @huangjr and I simply modified it. We didn't think too deeply about this.
@stozuka chose Nokogiri because he could find more information about Nokogiri than he could about Oga.

**Comment by soumyaray** [comment]
This is true.  Nokogiri is better documented.  But the xpath parts are exactly the same.

I'm totally fine with your using Nokogiri!  Case closed for me :)
