### ISSUE TITLE
Gem name doesn't match require statement

### ISSUE THREAD

**Issue by soumyaray** [SOAupstart2/Team-HW-1-Ideate-and-Scrape#19]
Programmer happiness issue here: anyone using your gem has to install something called soa_codeschool, but then require something called 'scrape'.  Can you make the required file file (scrape.rb) have a more suitable name?  perhaps the same name as the gem (soa_codeschol)?  

Normally this would a 'breaking change' and would require a change in major version (e.g., 1.x.x -> 2.x.x) but since you're in 0.x.x, its understood that every change can be a breaking one!

**Comment by stonegold546** [comment]
I think we've sorted this out. The required file has the same name as the gem.

**Comment by soumyaray** [comment]
:+1:
