### ISSUE TITLE
Make magic numbers into constants

### ISSUE THREAD

**Issue by soumyaray** [SOAupstart2/Team-HW-1-Ideate-and-Scrape#22]
xpath values like '//h2/a' and '//h3/a' are called magic strings when they are embedded in our code.  Might I suggest assigning those values to constants called something like COURSE_NAMES_XPATH and TEACHER_NAME_XPATH?  Then just reuse the constants in your code. It makes maintaining and changing things much easier in the future.

More on magic literals and why we don't want them in our code: https://eliotsykes.com/magic-numbers

**Comment by stonegold546** [comment]
I think they're gone. Saving them into reasonably named variables does make a whole lot of sense.

**Comment by soumyaray** [comment]
great!  i love closing issues!

**Comment by stonegold546** [comment]
Great! Same as we love attending them :)
